Oauth
teamdeepblue/caissa-chess pull request #16
Opened 2016-09-08 02:05 UTC by ShreyamsJain

Tested manually. Facebook login is working. Please review changes

2016-09-08 20:34 UTC, ShreyamsJain commented
Updated the environment variables(facebook tokens) in Codeship.

2016-09-08 20:57 UTC, ShreyamsJain commented
Resolved the conflicts. Ready for review

2016-09-08 22:28 UTC, erinmorrissey commented
@ShreyamsJain I'm trying to test the Facebook login — when I click "Sign In with Facebook", I get redirected to this FB error page: https://www.facebook.com/v2.6/dialog/oauth?client_id&display=popup&redirect_uri=http%3A%2F%2Flocalhost%3A3030%2Fusers%2Fauth%2Ffacebook%2Fcallback&response_type=code&scope=email&state=9c905c8bdb4b36d03f2bd7bcffdb20fc0086c1ee2af3f71c

Server log gives this:
`Started GET "/users/auth/facebook" for 10.0.2.2 at 2016-09-08 22:26:07 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
I, [2016-09-08T22:26:07.100748 #4182]  INFO -- omniauth: (facebook) Request phase initiated.`

I'm still googling to see what it could be, just thought I'd bring it up in case you happened to encounter it previously?

2016-09-09 05:58 UTC, ShreyamsJain commented
@erinmorrissey I was facing this issue yesterday, i just dont remember how i fixed it. When you are redirected to the facebook page, are you getting the error "invalid app id"?. Meanwhile i will search and let you know if how i fixed this error.

2016-09-09 13:25 UTC, lasley commented
only the secret should go in environment vars. You'll still need the `FACEBOOK_APP_ID` var added to your omniauth middleware in the same way you did before the env vars

2016-09-09 19:53 UTC, ShreyamsJain commented
Made the necessary changes(Added APP_ID to devise.rb) and resolved the conflicts.

2016-09-10 15:23 UTC, erniejamison commented
Might be working but I'm getting this error from facebook:

App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

2016-09-13 05:51 UTC, ShreyamsJain commented
Sorry for the late response @erniejamison . I checked in facebook settings and there is an option to add developers and testers. If you could tell me your username on Facebook, i can add you as a developer. I suppose, you have to be in my friend list to be added as a developer. Send me a request. My name is Shreyams Jain on fb.

2016-09-13 05:51 UTC, lasley commented
@ShreyamsJain - The app should be in production mode for our production server

2016-09-13 06:03 UTC, ShreyamsJain commented
@lasley Ok. There was an option to add developers and testers, so i thought probably the app is in development mode and requires to grant access. There was another option to make the app public and i just turned it on. Maybe it should work now for Ernie.

2016-09-13 20:57 UTC, lasley commented
@ShreyamsJain - The implementation looks good, but we will need to fix the build errors + add tests

* https://github.com/omniauth/omniauth/wiki/Integration-Testing
* https://gist.github.com/kinopyo/1338738
* https://gist.github.com/spyou/1200365

2016-09-29 00:38 UTC, ShreyamsJain commented
@erniejamison The files i have been working with are sessions_controller_spec.rb, rails_helper.spec, factories/omniauth.rb. Please ignore support/omniauth_macros.rb

2016-10-06 20:41 UTC, lasley requested changes

2016-10-06 20:41 UTC, lasley commented on app/models/pieces/untitled.Appraisals
> +class King < Piece
What is this file?

2016-10-06 20:41 UTC, lasley commented on .rubocop.yml
> +Style/BracesAroundHashParameters:
Why this change?

2016-10-06 20:41 UTC, lasley commented on app/views/devise/registrations/new.html.erb
> +
Why this change?

2016-10-06 20:41 UTC, lasley commented on coverage/.last_run.json
>  {
Remove this file

2016-10-06 20:41 UTC, lasley commented on coverage/.resultset.json
>  {
Remove this file

2016-10-06 20:41 UTC, lasley commented on coverage/assets/0.10.0/application.css
> +/* -----------------------------------------------------------------------
Remove this file

2016-10-06 20:41 UTC, lasley commented on coverage/.last_run.json
>  {
(this whole coverage folder needs to be deleted)

2016-10-10 19:19 UTC, lasley commented
Hey @ShreyamsJain - we have a conflict on the controller spec due to my #38. Will need to resolve please.

2016-10-11 06:37 UTC, ShreyamsJain commented
Hi @lasley , i updated my mac os to Sierra and after that i am unable to launch vagrant. Working on fixing that issue. Will resolve the above conflicts as soon as i get vagrant back working.

2016-10-11 20:22 UTC, ShreyamsJain commented
@lasley This conflicts are resolved.

2016-10-12 11:51 UTC, lasley requested changes

2016-10-12 11:51 UTC, lasley commented on .gitignore
> +/config/application.yml
Why?

2016-10-12 17:17 UTC, ShreyamsJain commented
Hi @lasley . This has been removed from gitignore

2016-10-13 23:04 UTC, lasley approved these changes

2016-10-14 04:33 UTC, erinmorrissey commented
I was going to approve and merge this, but the codecov scores are preventing it, at reasonable diffs for this particular PR, I would say. I saw in codecov.yml where we manually set a coverage range of 80-100, but don't see if there's a GitHub setting that would cause a 90% score to cause a failing check...?

2016-10-14 11:01 UTC, lasley commented
You can alway override the checks with admin rights. The issue is the diff, not the total. 10% diff from target will pretty much never be considered acceptable. There's a setting in the Codecov YML but I can't remember it TBH

2016-10-14 11:01 UTC, merged