models for different piece types
teamdeepblue/caissa-chess pull request #21
Opened 2016-09-14 21:31 UTC by wdehaes

I added the (for now empty) piece subclasses. I am not sure how to write tests for this because there is no functionality to test yet. Any suggestions?

2016-09-15 00:13 UTC, erinmorrissey commented
LGTM based on what I read about STI...just add trailing newlines to the 6 new model files so the build passes. I would think you don't need any tests written at this point since you're just building the initial model structure. Though you could build the factories for the pieces as another PR.

2016-09-15 14:55 UTC, lasley commented
@wdehaes tests for this would really just amount to the creation and testing of the factories for these models.

I would also do an STI check & make sure you can obtain the type a piece is. 

We should also probably add validation on the Piece model to make sure that type is a correct value. That's just a nice to have though, not a blocker.

2016-09-19 16:34 UTC, erniejamison commented
This is a work in progress. Factories for individual piece types were added. An STI check for the correct piece is needed and possibly validation.

2016-09-21 09:37 UTC, wdehaes commented
I added tests for the different pieces, using a shared example folder so we can add future tests for shared behavior in there. (http://stackoverflow.com/questions/14546621/testing-rails-sti-subclasses-with-rspec) (https://www.relishapp.com/rspec/rspec-core/v/3-5/docs/example-groups/shared-examples).

2016-09-23 22:31 UTC, lasley commented on coverage/.last_run.json
> +{
Will need to remove coverage- it was modified in this branch after merge of #30, so it will make it back in

2016-09-23 22:32 UTC, lasley commented on coverage/.resultset.json
> +{
Remove

2016-09-23 22:33 UTC, lasley requested changes
Excellent @wdehaes 

Few comments inline. Please also remove the `.DS_STORE` files.

2016-09-27 23:53 UTC, wdehaes commented on coverage/.last_run.json
> +{
👍 done

2016-09-27 23:53 UTC, wdehaes commented on coverage/.resultset.json
> +{
done

2016-09-28 04:35 UTC, lasley commented
@wdehaes - There are still `.DS_STORE` files present in the diff. You should also add them to `gitignore` in order to not re-add them

2016-09-30 22:41 UTC, ShreyamsJain commented
Hi Will @wdehaes , when do you plan to merge this PR?

2016-10-01 12:40 UTC, wdehaes commented
@ShreyamsJain Everything is ready to be merged, but two of the king rspec tests aren't working. I have no idea why. Any help would be much appreciated.

2016-10-01 16:50 UTC, ShreyamsJain commented
Sure @wdehaes . I was checking the STI branch ,was going through the games_controller_spec, couldn't find anything related to the king. Have you pushed the latest code to your branch?

2016-10-01 17:12 UTC, wdehaes commented
@ShreyamsJain The tests are for the model, not the controller, so you you should look in spec/models/king_spec.rb

2016-10-01 17:43 UTC, ShreyamsJain commented
Ok @wdehaes. I got it . Its failing in my computer as well. I will check and let you know if i find any solution.

2016-10-01 19:07 UTC, ShreyamsJain commented
Hey Will @wdehaes .. Got this working.. Delete the King.rb file that you have created in app/models/pieces/king.rb and run bundle exec rspec

2016-10-01 21:33 UTC, wdehaes commented
@ShreyamsJain Thanks, I totally looked over that. Fixed it

2016-10-01 22:22 UTC, ShreyamsJain commented
Awesome

2016-10-02 06:44 UTC, lasley approved these changes
Sweet this looks excellent, thanks @wdehaes 

Note - putting the pieces in a pieces folder was totally the right way to go about it. I want to say I've only seen it one other time in the team projects - that additional autoload in the config usually throws newbs off

2016-10-03 06:39 UTC, ShreyamsJain approved these changes
LGTM

2016-10-03 12:16 UTC, lasley commented
Let me know once the conflicts are fixed & I'll final check + merge

2016-10-04 05:40 UTC, lasley commented
resolution looks good, merging

2016-10-04 05:40 UTC, merged