Change codecov.yml and set it with default values
teamdeepblue/caissa-chess pull request #25
Opened 2016-09-17 06:19 UTC by ShreyamsJain

2016-09-17 14:44 UTC, lasley commented on codecov.yml
> +# below in your own codecov.yml in your repository.
You can remove this comment

2016-09-17 14:44 UTC, lasley commented on codecov.yml
> +  range: 70...100
IMO 80...100 is better, but that's up to you guys.

70% is a C, which is average. Do you strive for average or excellence?

2016-09-17 14:45 UTC, lasley commented on codecov.yml
> +  behavior: default  # update if exists else create new
All lines should end with a carriage return https://robots.thoughtbot.com/no-newline-at-end-of-file

2016-09-17 14:45 UTC, lasley requested changes

2016-09-21 01:28 UTC, ShreyamsJain commented on codecov.yml
> +  behavior: default  # update if exists else create new
@lasley I have performed the necessary changes

2016-09-21 01:29 UTC, lasley approved these changes

2016-09-21 01:31 UTC, merged