Isobstructed
teamdeepblue/caissa-chess pull request #27
Opened 2016-09-18 15:43 UTC by erniejamison

This is close but need to be looked over. Instead of just returning true or false the code there is an extra method that returns an array of obstructing pieces. By convention a Ruby method ending with a '?' returns true or false so I separated it and called #obstructing_pieces with it.

2016-09-20 08:00 UTC, lasley commented on app/models/piece.rb
> +    elsif moving_diagonally? # needs word
needs word?

2016-09-20 08:01 UTC, lasley commented on spec/models/piece_spec.rb
> +      Piece.create(game_id: game.id, x_position: 3, y_position: 0)
This create should be in a before or a let statement in order to DRY

2016-09-20 08:02 UTC, lasley commented on spec/models/piece_spec.rb
> +      Piece.create(game_id: game.id, x_position: 5, y_position: 0)
You should then base this create off of the one that was created centrally

2016-09-20 08:02 UTC, lasley commented on spec/models/piece_spec.rb
> +      Piece.create(game_id: game.id, x_position: 0, y_position: 6)
You should then base this create off of the one that was created centrally

2016-09-20 08:02 UTC, lasley commented on spec/models/piece_spec.rb
> +      Piece.create(game_id: game.id, x_position: 0, y_position: 2)
You should remove this

2016-09-20 08:02 UTC, lasley commented on spec/models/piece_spec.rb
> +      Piece.create(game_id: game.id, x_position: 4, y_position: 4)
You should then base this create off of the one that was created centrally

2016-09-20 08:02 UTC, lasley commented on spec/models/piece_spec.rb
> +      Piece.create(game_id: game.id, x_position: 0, y_position: 0)
You should remove this

2016-09-20 08:05 UTC, lasley commented on spec/models/piece_spec.rb
> +  end
Please also add negative test cases - what if I'm not obstructed horizontally, vertically, or diagonally? You'd be surprised how often the negative cases break

2016-09-20 08:06 UTC, lasley commented on app/models/piece.rb
> +  def obstructing_pieces(x_destination, y_destination)
I would call this `get_obstructing_pieces`. Typically should follow a `verb_adverb_noun_prounoun` type order

2016-09-20 08:08 UTC, lasley commented on app/models/piece.rb
> +      pieces = Piece.where(game_id: game.id, y_position: y_start, x_position: (x_start + 1..x_destination - 1)).exists?
A lot of repetition here, what if you instead
* set default variables for `y_position` (y_start) and `x_position` (x_start) 
* then modify them in the ifs (`_start + 1..x_destination - 1)`)
* then perform one query afterwards on the vars

2016-09-20 08:08 UTC, lasley requested changes

2016-09-20 08:08 UTC, lasley commented on .byebug_history
> +c
Should this be checked into source control? Maybe make a PR to add to `.gitignore`?

2016-09-20 08:08 UTC, lasley commented on app/models/.byebug_history
> +step
Should this be checked into source control? Maybe make a PR to add to `.gitignore`?

2016-09-20 08:08 UTC, lasley commented on app/models/piece.rb
> +    obstructing_pieces(x_destination, y_destination)
Why just calling a method? Are you instead trying to [typecast to bool](http://rubyquicktips.com/post/583755021/convert-anything-to-boolean)?

2016-09-20 08:08 UTC, lasley commented on coverage/.last_run.json
> +{
Add this directory `coverage/*` to gitignore as part of the PR previously mentioned

2016-09-20 08:08 UTC, lasley commented on coverage/.resultset.json
> +{
Add this directory `coverage/*` to gitignore as part of the PR previously mentioned

2016-09-20 18:51 UTC, erniejamison commented on app/models/piece.rb
> +    elsif moving_diagonally? # needs word
work

2016-09-20 18:51 UTC, erniejamison commented on .byebug_history
> +c
So I'd have to create a new branch?

2016-09-22 13:17 UTC, erniejamison commented on .byebug_history
> +c
Taken care of in another branch

2016-09-24 18:22 UTC, erniejamison commented on app/models/piece.rb
> +      pieces = Piece.where(game_id: game.id, y_position: y_start, x_position: (x_start + 1..x_destination - 1)).exists?
I am stuck on this and need to get help with it.

2016-09-25 18:17 UTC, lasley commented
@erniejamison - This issue is marked as Help Wanted, but I don't see any sort of issues detailed here. Is this incorrectly tagged?

2016-09-25 20:14 UTC, erniejamison commented
I am going in circles trying to implement the reviews and rewrite the code.

2016-09-25 22:48 UTC, erniejamison commented
I am switching this back to returning true/false instead of an array. That is all it needs to do. I'm still working on the diagonal case. Not sure why the files and directories that have been added to .gitignore showed up.

2016-09-27 21:05 UTC, erniejamison commented
Please review. So close. Advise on rubocop offenses. Do I need to break up the if/else in the obstructed? method? Will that take care of the 'Assignment Branch Condition size for obstructed? is too high' error?

2016-09-27 21:49 UTC, erniejamison commented
Ready for review

2016-09-27 22:46 UTC, erinmorrissey commented on app/models/piece.rb
> +        pieces.concat(Piece.where(x_position: x, y_position: y))
Wouldn't we also want to verify `game.id` here?

2016-09-27 22:46 UTC, erinmorrissey commented on app/models/piece.rb
> +    if moving_horizontally?(x_destination, y_destination)
Is there a reason for passing in `x_destination` when only `y_destination` is needed for the method?

2016-09-27 23:20 UTC, erniejamison commented on app/models/piece.rb
> +    if moving_horizontally?(x_destination, y_destination)
Possibly not I'll check it out

2016-09-27 23:21 UTC, erniejamison commented on app/models/piece.rb
> +        pieces.concat(Piece.where(x_position: x, y_position: y))
Probably I'll look at it

2016-09-27 23:49 UTC, erinmorrissey commented on app/models/piece.rb
> +    if moving_horizontally?(x_destination, y_destination)
Inside of the `moving_horizontally?` method, only the `y_destination` argument is used. Just seems cleaner to change `moving_horizontally?` to accept only 1 argument and change the `if moving_horizontally?` method call to pass only 1 argument, but I wasn't sure if I was missing something. Same would go for the `moving_vertically?` method...

2016-09-28 00:09 UTC, erniejamison commented
Ready for review

2016-09-28 00:09 UTC, erniejamison commented on app/models/piece.rb
> +    if moving_horizontally?(x_destination, y_destination)
I got you. Makes sense. Thanks

2016-09-28 20:42 UTC, lasley commented on .byebug_history
> +c
This file still needs to be removed from this diff

2016-09-28 20:43 UTC, lasley commented on app/models/.byebug_history
> +step
This file should be removed

2016-09-28 20:43 UTC, lasley requested changes
Minor fixes, just file deletions. Everything else 👍

2016-09-29 01:51 UTC, lasley approved these changes

2016-09-29 01:51 UTC, lasley commented
Thanks @erniejamison

2016-09-29 02:27 UTC, erinmorrissey commented
👍  merging!

2016-09-29 02:27 UTC, merged