Add valid_move? logic for Piece & King
teamdeepblue/caissa-chess pull request #31
Opened 2016-09-23 19:22 UTC by erinmorrissey

Added initial valid_move? logic for the Piece & King models. I didn't include castling logic as that's a  separate ticket. Looking for code reviews/comments at this point, but I still have to write the tests.

2016-09-23 22:24 UTC, lasley commented on app/models/king.rb
> +    return false if super(x_destination, y_destination) == false
`return false unless super(x_destination, y_destination)`

2016-09-23 22:26 UTC, lasley commented on app/models/piece.rb
> +  def x_diff(x_destination)
Maybe combine these two methods, and just accept start & end coords instead of using the instance vars?

2016-09-23 22:29 UTC, lasley commented on app/models/piece.rb
> +    return false if !(0..7).cover?(x_destination) || !(0..7).cover?(y_destination)
Might want to centralize board boundaries in the superclass, no piece can move off the board

2016-09-23 22:30 UTC, lasley requested changes

2016-09-25 19:29 UTC, erinmorrissey commented on app/models/piece.rb
> +    return false if !(0..7).cover?(x_destination) || !(0..7).cover?(y_destination)
Not sure what you mean here, isn't the Piece model the superclass? Or do you mean define the boundaries on the model somehow?

2016-09-26 00:33 UTC, lasley commented on app/models/piece.rb
> +    return false if !(0..7).cover?(x_destination) || !(0..7).cover?(y_destination)
Ahh yup ignore me on this, you did it right I just misread file name

2016-09-27 21:45 UTC, erinmorrissey commented
@lasley I refactored the methods based on your comments and added tests, this should be ready for review.

2016-09-28 04:41 UTC, lasley approved these changes
One non-blocking comment. 👍

2016-09-28 04:41 UTC, lasley commented on app/models/king.rb
> +    return false if x_diff_val > 1 || y_diff_val > 1
These two returns can be simplified as `return !(x_diff_val > 1 || y_diff_val > 1)`

2016-09-28 21:23 UTC, erniejamison commented
Merging. 👍

2016-09-28 21:23 UTC, merged