Populate game backend
teamdeepblue/caissa-chess pull request #32
Opened 2016-09-25 06:43 UTC by ShreyamsJain

Sets the pieces in its initial x and  position.
Performs x and y position validation as well as validation for number of pieces created.

2016-09-25 18:09 UTC, lasley commented on db/migrate/20160925060545_change_column_name_in_pieces.rb
> +  	rename_column :pieces, :type, :piece_name
What is the reasoning behind this change?

2016-09-25 18:10 UTC, lasley commented on app/controllers/pieces_controller.rb
> +  def new
How can you prove this works without tests?

2016-09-25 18:10 UTC, lasley commented on app/controllers/pieces_controller.rb
> +  def set_white_pieces
How can you prove this works without tests?

2016-09-25 18:10 UTC, lasley commented on app/controllers/pieces_controller.rb
> +  def set_black_pieces
How can you prove this works without tests?

2016-09-25 18:10 UTC, lasley commented on app/models/piece.rb
> +  def validate_max_pieces
How can you prove this works without tests?

2016-09-25 18:11 UTC, lasley commented on coverage/.last_run.json
> +{
Please remove this file. It should be in the gitignore on master now too, so it should not continue to be added.

2016-09-25 18:11 UTC, lasley commented on coverage/.resultset.json
> +{
Please remove this file. It should be in the gitignore on master now too, so it should not continue to be added.

2016-09-25 18:13 UTC, lasley commented on app/controllers/pieces_controller.rb
> +      pawn_pos += 1
This seems unnecessary. You should be able to obtain the loop iteration count from the loop, then use it +1 for the x_pos

2016-09-25 18:15 UTC, lasley commented on app/models/piece.rb
> +    errors[:base] << 'Only 32 pieces are allowed.' if Piece.count == 32
I feel like this will fail after another game is created. Please add a test to prove me wrong.

2016-09-25 18:15 UTC, lasley requested changes

2016-09-25 18:27 UTC, ShreyamsJain commented on db/migrate/20160925060545_change_column_name_in_pieces.rb
> +  	rename_column :pieces, :type, :piece_name
@lasley When i was writing validations for the type column, i was getting an error," Invalid Single table inheritance type". Then i found out that 'type' is a reserved keyword in ActiveRecord. So i changed it. Later i checked @wdehaes 's code for STI branch, i found out he had created sub classes for pieces. Then i was wondering if using type as column was preplanned so it validates using only subclasses. Am i correct? I thought of removing the entire validation and renaming the column back to type, but wanted your reviews before changing it.

2016-09-25 18:46 UTC, lasley commented on db/migrate/20160925060545_change_column_name_in_pieces.rb
> +  	rename_column :pieces, :type, :piece_name
You are correct that `type` is used for STI & that the validations are already under the hood ;)

2016-10-06 20:48 UTC, lasley requested changes

2016-10-06 20:48 UTC, lasley commented on coverage/.resultset.json
>  {
Remove this file

2016-10-06 20:48 UTC, lasley commented on spec/factories/bishop.rb
> +    player_id 1
How do you know this player exists? You should use an association https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md

2016-10-10 20:54 UTC, wdehaes commented on coverage/.resultset.json
>  {
I think I managed to remove these

2016-10-10 22:00 UTC, wdehaes commented
@ShreyamsJain I made some minor adjustments, other than that the code looks good to me, though I am not sure if the tests cover everything (are the pieces in the right place, etc). 

Just a question, it doesn't seem like you hooked up the PiecesController#new method to the GamesController, or am I wrong? @lasley not sure if this is supposed to be part of this ticket

2016-10-10 22:48 UTC, lasley approved these changes

2016-10-10 22:48 UTC, lasley commented
@wdehaes - This ticket was supposed to be model only, and has spiraled out of control in terms of scope. We should not add any more logic

2016-10-10 23:13 UTC, merged