Pawn
teamdeepblue/caissa-chess pull request #41
Opened 2016-10-10 18:49 UTC by wdehaes

Created the valid_move? method for pawn + rspec tests. Also made some corrections to obstructed? method in piece.rb (will change in rook PR as well)

2016-10-11 08:25 UTC, lasley requested changes
comments inline

2016-10-11 08:25 UTC, lasley commented on app/models/pieces/pawn.rb
> +    return false if moving_horizontally?(y_destination) || diff(x_destination, x_position) > 1 || diff(y_destination, y_position) > 2
You can probably eliminate the `diff(y_destination, y_position) > 2` in favor of the explicit check later (except using `>=` instead).

2016-10-11 08:25 UTC, lasley commented on app/models/pieces/pawn.rb
> +    if diff(x_destination, x_position).zero?
The x and y diffs are being calculated a lot. Might be best to create an x_diff, y_diff intermediary var

2016-10-11 08:25 UTC, lasley commented on app/models/pieces/pawn.rb
> +  # rubocop:disable all
It is best practice to only disable the specific cop that is failing & unable to be resolved. I assume it is ABCSize & PerceivedComplexity?

2016-10-13 10:01 UTC, wdehaes commented on app/models/pieces/pawn.rb
> +    return false if moving_horizontally?(y_destination) || diff(x_destination, x_position) > 1 || diff(y_destination, y_position) > 2
I don't understand how that would work. My logic was that a move with diff_y > 2 is always invalid, but a move with diff_y == 2 can be valid in some cases.

2016-10-13 10:01 UTC, wdehaes commented on app/models/pieces/pawn.rb
> +  # rubocop:disable all
Yep

2016-10-13 21:53 UTC, erniejamison commented
LGTM 👍

2016-10-13 22:57 UTC, lasley approved these changes

2016-10-13 23:01 UTC, merged